#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=5:00:00

[ $PBS_O_WORKDIR ] && cd $PBS_O_WORKDIR

## modules
echo "Loading modules"
module load ants
module unload matlab
module load matlab/2017a
module load spm/8
module unload python
module load dipy/dev
module load nodejs
echo "Finished loading modules"

export PYTHONPATH=/N/u/brlife/git/nibabel:$PYTHONPATH

# Check the inputs subject id
echo "Check the inputs subject id"
t1_sub1_id=`jq -r '._inputs[0].meta.subject' config.json`
fa_sub1_id=`jq -r '._inputs[1].meta.subject' config.json`
t1_sub2_id=`jq -r '._inputs[2].meta.subject' config.json`
fa_sub2_id=`jq -r '._inputs[3].meta.subject' config.json`
if [ $fa_sub1_id == $t1_sub1_id -a $fa_sub2_id == $t1_sub2_id ]; then
	echo "Inputs subject IDs correctly inserted"
else
	echo "Inputs subject IDs incorrectly inserted. Check them again."
	exit 1
fi

# ANTs transformation
echo "ANTs transformation"
./voxel_based_transformation_karst.sh ${t1_sub1_id} ${t1_sub2_id} 


ret=$?
if [ ! $ret -eq 0 ]; then
	echo "ANTs transformation failed"
	echo $ret > finished
	exit $ret
fi

ret=$?
if [ ! $ret -eq 0 ]; then
	echo "DSC computation failed"
	echo $ret > finished
	exit $ret
fi

echo "Complete"
